### ISSUE TITLE
[BUG] Documentation contains broken links to a non existing examples folder

### ISSUE THREAD

**Issue by xalvarez** [otto-de/b2b-design-system#208]
**Describe the bug**
The documentation contains broken links to a non existing *examples* folder under the old *otto-ec/b2b-design-system* repository.

I don't know what would be the correct link to be used in this case so I can't fix the issue on my own.

**To Reproduce**
Search for `*.mdx` files containing *otto-ec/b2b-design-system* in this repository's files.

**Comment by AnnaHoege** [comment]
Hi @xalvarez, thanks for contributing! 
We will take a look as we are currently migrating our Storybook anyway. I'll update this thread when the issues are resolved.

**Comment by AnnaHoege** [comment]
Closed with merging B2BDS-212
