### ISSUE TITLE
[REQUEST] Add an calendar component

### ISSUE THREAD

**Issue by brandtf2512** [otto-de/b2b-design-system#250]
We asked ourself if its possible to add an calendar component. We currently facing the issue that we need more customization then the standard HTML5 input field of type date.

What we have:
![grafik](https://github.com/otto-de/b2b-design-system/assets/115005433/2ce09c60-92a5-436a-ae46-b305fa1ebfd3)
- only min and max can be set

What it should provide:
- mark an list of given dates like here the 25th
![grafik](https://github.com/otto-de/b2b-design-system/assets/115005433/b0078d2a-c2ae-4653-b11b-9d661b8029f1)

**Comment by vishwapriya** [comment]
The date picker component has already released:
 https://b2b-design-system.otto.market/?path=/docs/components-form-date-picker--docs
