### ISSUE TITLE
[BUG] [B2bInputList] On "disabled", content still can be cleared

### ISSUE THREAD

**Issue by thonit** [otto-de/b2b-design-system#335]
**Describe the bug**
After an input list has been set to disabled, it is still possible to remove the content using the X. Is there a way to deactivate this as well, or are there reasons why this is not currently the case?

**Expected behavior**
After disabling the input list, also the X should be disabled.

**Screenshots**
https://github.com/otto-de/b2b-design-system/assets/150906584/0655bb0b-6846-4c35-9eb9-04e3b108b9d3

**Framework Used**
 - local development

**Package**
- Version 1.6.1
- @otto-de/b2b-react-components'

**Comment by AnnaHoege** [comment]
Hi @thonit,

thanks for your submission! This issue will be fixed in the next release. Check our teams channel to stay updated on upcoming features!
