### ISSUE TITLE
[REQUEST] [b2b-search] trigger search on ENTER

### ISSUE THREAD

**Issue by OTTOxMarc** [otto-de/b2b-design-system#77]
I am on version 1.3.0.

Could you enhance the `b2b-search` so the `@b2b-search` event is not only triggered when pressing the search icon but also when pressing the <kbd>Enter</kbd> key?

**Comment by mduenias** [comment]
Hi @OTTOxMarc, Thanks for submitting this issue! very important indeed!

This has been fixed and would be included in our next release.
Keep an eye to our comms channels for when that happens. We will update this issue as well.
