### ISSUE TITLE
[REQUEST] [b2b-icon] Calendar

### ISSUE THREAD

**Issue by OTTOxMarc** [otto-de/b2b-design-system#79]
Many microservices use the following icon to toggle a date picker.

![image](https://github.com/otto-de/b2b-design-system/assets/65161626/8e3732c8-0314-469e-9ca7-947e76b587d4)

The only date related icons are the following

![image](https://github.com/otto-de/b2b-design-system/assets/65161626/92201e2d-aee8-43a5-9f2a-f171915533ad)

But they could also resemble sticky notes. Is it planned to add a "real" calendar icon?

**Comment by mduenias** [comment]
Hi @OTTOxMarc, I will take this request to the design team and get back to you as soon as we have more info.

**Comment by mduenias** [comment]
Hi @OTTOxMarc, there are two icons that might be a bit closer to what you need, and design confirm they can be used in the date picker:

![Screenshot 2023-06-14 at 12 01 31](https://github.com/otto-de/b2b-design-system/assets/15000807/5587f651-2047-4430-81fa-8000c571417b)

Let us know if this ones work for you.

**Comment by AnnaHoege** [comment]
Hi @OTTOxMarc, any feedback on this? Otherwise we'd like to close the issue. :)

**Comment by OTTOxMarc** [comment]
Hey @AnnaHoege, sorry for not getting back to you. These icons are exactly what I was looking for, thx 👍
