### ISSUE TITLE
[REQUEST] [b2b-breadcrumb] Add a breadcrumb control

### ISSUE THREAD

**Issue by OTTOxMarc** [otto-de/b2b-design-system#80]
I searched the docs and the repo, but I couldn't find a breadcrumb control. Is it planned to add this to the design system?

**Comment by mduenias** [comment]
Hi @OTTOxMarc. Yes that component is in our backlog but it does not have a high priority. If your team will need it soon, we can add it to the higher priority list and try to tackle it sooner. Let me know by when would you need it :)

**Comment by matthiasstroeh6380** [comment]
Also team Turtle would like to have such a component. 👍

**Comment by brandtf2512** [comment]
Our team is also interested to use such an component. So I initiated an first draft in here #116. Could you please take a look.

**Comment by AnnaHoege** [comment]
Update: Breadcrumb is reviewed and improved and will be shipped in the next release v1.7.0
Thanks again @brandtf2512 ! <3
